SD.WEB/SD.WEB/ViewModels/StadiumViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FantasyData.Api.Client.Model.NFLv3;

namespace SD.WEB.ViewModels
{
    public class StadiumViewModel
    {
        public Stadium Stadium { get; set; }
        public string GoogleImage { get; set; }
    }
}

SD.WEB/SD.WEB/ViewModels/StadiumsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FantasyData.Api.Client.Model.NFLv3;

namespace SD.WEB.ViewModels
{
    public class StadiumsViewModel
    {
        public List<Stadium> Stadiums { get; set; }
    }
}

SD.WEB/SD.WEB/ViewModels/TeamViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FantasyData.Api.Client.Model.NFLv3;

namespace SD.WEB.ViewModels
{
    public class TeamViewModel
    {
        public Team Team { get; set; }
    }
}

SD.WEB/SD.WEB/ViewModels/TeamsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FantasyData.Api.Client.Model.NFLv3;

namespace SD.WEB.ViewModels
{
    public class TeamsViewModel
    {
        public List<Team> Teams { get; set; }
    }
}

SD.WEB/SD.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SD.WEB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SD.WEB/SD.WEB/Controllers/NFLStadiumsController.cs
using SD.WEB.Services;
using SD.WEB.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SD.WEB.Controllers
{
    public class NFLStadiumsController : Controller
    {
        private NFLService _nflService;
        private GoogleService _googleService;

        public NFLStadiumsController()
        {
            _nflService = new NFLService();
            _googleService = new GoogleService();
        }
        // GET: NFLStadiums
        public ActionResult GetAllStadiums()
        {
            var model = new StadiumsViewModel
            {
                Stadiums = _nflService.GetAllStadium()
            };
            return View(model);
        }
        // GET: NFLStadiums/id
        public ActionResult GetStadium(int id)
        {
            var stadium = _nflService.GetStadiumById(id);
            string googleImageUrl = _googleService.AssembleGoogleImageString(stadium.GeoLat, stadium.GeoLong);

            StadiumViewModel model = new StadiumViewModel
            {
                Stadium = stadium,
                GoogleImage = googleImageUrl
            };
            return View("Stadium",model);
        }

    }
}

SD.WEB/SD.WEB/Controllers/NFLTeamsController.cs
using SD.WEB.Services;
using SD.WEB.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SD.WEB.Controllers
{
    public class NFLTeamsController : Controller
    {
        private NFLService _nflService;

        public NFLTeamsController()
        {
            _nflService = new NFLService();
        }
        // GET: NFLTeams/GetAllTeams
        public async Task<ActionResult> GetAllTeams()
        {
            var model = new TeamsViewModel
            {
                Teams = await _nflService.GetAllTeams()
            };
            return View(model);
        }

        // GET: NFLTeams/GetTeam/5
        public async Task<ActionResult> GetTeam(int id)
        {
            var model = new TeamViewModel
            {
                Team = await _nflService.GetTeam(id)
            };
            return View("GetTeam",model);
        }

        
    }
}

SD.WEB/SD.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SD.WEB/SD.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SD.WEB/SD.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="nfl-stats-banner-home">
    <div class="container">
        <div class="row content-banner">
            <h1>Sports Data Using ASP.NET</h1>
            <p class="lead">Quickly and easily use FantasyData with just 7 lines of code!</p>
            <p class="content-banner-buttons">
             <a href="https://github.com/mike1477/nflservice" target="_blank" class="btn btn-primary btn-lg">Visit GitHub &raquo;</a>
             <a href="https://fantasydata.com" target="_blank" class="btn btn-primary btn-lg">FantasyData Website &raquo;</a>
            </p>
        </div>
    </div>  
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 top-para-home">
            <p>
                The FantasyData Sport Delivery .NET library allows you to easily get any type of sport data supported by our fast API, from a simple game to complex sport stats. We have you covered.
            </p>
        </div>

    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 top-para-home">
            <h2>YOUR KEY</h2>
            <p>
                When you create your free account you should of got a key.
                In your web.config file paste the code below inside the
                <span class="highlight"> &lt; appSettings &gt;</span>
            </p>
            <div class="jumbotron code-container">
                <code> &lt;add key="SportDataKey" value="[ YOUR API KEY]" /&gt;</code>
            </div>

            <p class="content-code-buttons">
                <a href="https://fantasydata.com/user/register" target="_blank" class="btn btn-success btn-lg">Sign up & Get Key &raquo;</a>
                <a href="https://github.com/mike1477/nflservice/blob/master/SD.WEB/SD.WEB/Web.config" target="_blank" class="btn btn-success btn-lg">GitHub Example &raquo;</a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 top-para-home">
            <h2>CONTROLLER</h2>
            <p>
                At the top of the <span class="highlight"> HomeController.cs </span> add the code below.
            </p>
            <div class="jumbotron code-container">
                <code>
                    private readonly string SportDataKey = WebConfigurationManager.AppSettings["SportDataKey"];<br />
                    private NFLv3StatsClient _client;<br />

                    public HomeController()<br />
                    {
                    _client = new NFLv3StatsClient(SportDataKey);
                    }
                </code>
            </div>
            <p>
                There are many ways to intergrate APIs into you application. This is just one way.
                Open your <span class="highlight"> HomeController.cs </span> and paste code below into the Index method.
            </p>
            <div class="jumbotron code-container">
                <code>
                    var stadiums = _client.GetStadiums();<br>
                    return View(stadiums);
                </code>
            </div>

            <p class="content-code-buttons">
                <a href="https://github.com/mike1477/nflservice/tree/master/SD.WEB/SD.WEB/Controllers" target="_blank" class="btn btn-success btn-lg">GitHub Example &raquo;</a>
            </p>
        </div>

    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 top-para-home">
            <h2>View</h2>
            <p>
                Inside the <span class="highlight"> Index.cshtml</span> file add the code below
            </p>
            <div class="jumbotron code-container">
                <code>

                    &lt;h3&gt;Entire list of stadiums in the NFL&lt;/h3&gt; <br />


                    &lt;table style="width:100%" class="table"&gt;<br />
                    &lt;tr&gt;<br />
                    &lt;th&gt;Name&lt;/th&gt;<br />
                    &lt;th>City&lt;/th>
                    &lt;th&gt;PlayingSurface&lt;/th&gt;<br />
                    &lt;th&gt;&lt;/th&gt;<br />
                    &lt;/tr&gt;<br />
                    &#64;foreach (var stadium in Model.Stadiums)<br />
                    {
                    &lt; tr &gt;<br />
                    &lt; td &gt; &#64;stadium.Name &lt; td &gt;<br />
                    &lt; td &gt; &#64;stadium.City &lt;/ td &gt;<br />
                    &lt; td &gt; &#64;stadium.PlayingSurface &lt;/ td &gt;<br />
                    &lt; td &gt; &#64;Html.ActionLink("Location", "GetStadium", new { id = stadium.StadiumID }, new { &#64;class = "navbar-brand btn-success" }) &lt;/ td &gt;<br />
                    &lt;/ tr &gt;
                    }


                    &lt;/table&gt;<br />


                </code>
            </div>

            <p class="content-code-buttons">
                <a href="https://github.com/mike1477/nflservice/tree/master/SD.WEB/SD.WEB/Views" target="_blank" class="btn btn-success btn-lg">GitHub Example &raquo;</a>
            </p>
        </div>
    </div>
</div>
<div class="email">
    <p class="email-button">
        <a href="https://sportsdata.io/contact-us" target="_blank" class="btn btn-warning btn-lg glyphicon glyphicon-envelope"></a>
    </p>
</div>

SD.WEB/SD.WEB/Views/NFLStadiums/GetAllStadiums.cshtml
@using SD.WEB.ViewModels

@model StadiumsViewModel
@{
    ViewBag.Title = "GetAllStadiums";
}

<h3>Entire list of stadiums in the NFL</h3>


<table style="width:100%" class="table">
    <tr>
        <th>Name</th>
        <th>City</th>
        <th>PlayingSurface</th>
        <th></th>
    </tr>
        @foreach (var stadium in Model.Stadiums)
        {
        <tr>
            <td>@stadium.Name</td>
            <td>@stadium.City</td>
            <td>@stadium.PlayingSurface</td>
            <td>@Html.ActionLink("Location", "GetStadium",new {id = stadium.StadiumID }, new { @class = "navbar-brand btn-success" })</td>
        </tr>
        }

        
    </table>

SD.WEB/SD.WEB/Views/NFLStadiums/Stadium.cshtml
@using SD.WEB.ViewModels

@model StadiumViewModel
@{
    ViewBag.Title = "Stadium";
}




<div class="row">
    <div class="col-sm-6 col-md-6">
        <h2>Stadium</h2>
        <p>@Html.ActionLink("Go Back To Stadiums", "GetAllStadiums", "NFLStadiums", new { area = "" }, new { @class = "navbar-brand btn btn-primary" })</p>
        <div class="thumbnail">
            <img src="@Model.GoogleImage" alt="Google Map">
            <div class="caption">
                <h3>@Model.Stadium.Name</h3>
                <p>State : @Model.Stadium.State</p>
                <p>Playing Surface : @Model.Stadium.PlayingSurface</p>
            </div>
        </div>
    </div>
</div>

SD.WEB/SD.WEB/Views/NFLTeams/GetAllTeams.cshtml
@using SD.WEB.ViewModels

@model TeamsViewModel
@{
    ViewBag.Title = "GetAllTeams";
}

<h3>Entire list of stadiums in the NFL</h3>


<table style="width:100%" class="table">
    <tr>
        <th>Name</th>
        <th>City</th>
        <th>FullName</th>
        <th></th>
    </tr>
    @foreach (var Team in Model.Teams)
    {
        <tr>
            <td>@Team.Name</td>
            <td>@Team.City</td>
            <td>@Team.FullName</td>
            <td>@Html.ActionLink("Team Details", "GetTeam", new { id = Team.TeamID}, new { @class = "navbar-brand btn-success" })</td>
        </tr>
    }


</table>

SD.WEB/SD.WEB/Views/NFLTeams/GetTeam.cshtml
@using SD.WEB.ViewModels

@model TeamViewModel
@{
    ViewBag.Title = "Team";
}




<div class="row">
    <div class="col-sm-6 col-md-6">
        <h2>Team</h2>
        <p>@Html.ActionLink("Go Back To Teams", "GetAllTeams", "NFLTeams", new { area = "" }, new { @class = "navbar-brand btn btn-primary" })</p>
        <div>
            <h3>Team Name : @Model.Team.Name</h3>
            <p>Coach : @Model.Team.HeadCoach</p>
        </div>
    </div>
</div>

SD.WEB/SD.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NFL Stats", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("View All Stadiums", "GetAllStadiums", "NFLStadiums")</li>
                    <li>@Html.ActionLink("View All Teams", "GetAllTeams", "NFLTeams")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NFL Stats</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>